=== marcoalmeida-96/Dweb2019/TP2/Project_Record.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Project_Record (cabeçalho, workTeam, Abstract, deliverables) >

<!ELEMENT  cabeçalho (key_name, title, subtitle, begin_date, end_date, supervisor) >
<!ELEMENT  key_name (#PCDATA)>
<!ELEMENT  title (#PCDATA)>
<!ELEMENT  subtitle (#PCDATA)*>
<!ELEMENT  begin_date (#PCDATA)>
<!ELEMENT  end_date (#PCDATA)>
<!ELEMENT  supervisor (nome+, url+)>
<!ELEMENT  nome (#PCDATA)>
<!ELEMENT  url (#PCDATA)>

<!ELEMENT  workTeam (elementos_equipa+, identificador+, git+, email+)>
<!ELEMENT  elementos_equipa (#PCDATA)>
<!ELEMENT  identificador (#PCDATA)>
<!ELEMENT  git (#PCDATA)>
<!ELEMENT  email (#PCDATA)>

<!ELEMENT  Abstract (#PCDATA|links)*>
<!ELEMENT links (#PCDATA) >


<!ELEMENT  deliverables (link+) >
<!ELEMENT  link (#PCDATA)>

=== marcoalmeida-96/Dweb2019/TP2/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Project_Record SYSTEM "file:/D:/Uminho/4%C2%BA%20Ano/WEB/TP2/Project_Record.dtd">
<Project_Record>
    <cabeçalho>
        <key_name></key_name>
        <title></title>
        <subtitle></subtitle>
        <begin_date></begin_date>
        <end_date></end_date>
        <supervisor>
            <nome></nome>
        </supervisor>
    </cabeçalho>
    <workTeam>
        <elementos_equipa></elementos_equipa>
    </workTeam>
    <Abstract></Abstract>
    <deliverables>
        <link></link>
    </deliverables>
</Project_Record>
